# Generated by Django 5.2.17 on 2026-09-19 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("cif", models.CharField(blank=True, max_length=20)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PROPIETARIO", "Propietario"),
                            ("RSEG", "Responsable de Seguridad"),
                            ("TECNICO", "Técnico"),
                            ("COLABORADOR", "Colaborador de bloque"),
                            ("DIRECCION", "Dirección"),
                            ("AUDITOR", "Auditor"),
                            ("CONSULTOR", "Consultor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("systems", models.JSONField(blank=True, default=list)),
                ("bloques", models.JSONField(blank=True, default=list)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitación",
                "verbose_name_plural": "invitaciones",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PROPIETARIO", "Propietario"),
                            ("RSEG", "Responsable de Seguridad"),
                            ("TECNICO", "Técnico"),
                            ("COLABORADOR", "Colaborador de bloque"),
                            ("DIRECCION", "Dirección"),
                            ("AUDITOR", "Auditor"),
                            ("CONSULTOR", "Consultor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bloques", models.JSONField(blank=True, default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("PENDIENTE", "Pendiente"),
                            ("CADUCADA", "Caducada"),
                            ("REVOCADA", "Revocada"),
                        ],
                        default="ACTIVA",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitaciones_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "systems",
                    models.ManyToManyField(
                        blank=True, related_name="memberships", to="compliance.system"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user"), name="uniq_membership_tenant_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("objeto_tipo", models.CharField(blank=True, max_length=100)),
                ("objeto_id", models.CharField(blank=True, max_length=64)),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("hash", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada del registro",
                "verbose_name_plural": "registro de actividad",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["tenant", "id"], name="tenancy_aud_tenant__bd4754_idx")
                ],
            },
        ),
    ]
