# Generated by Django 5.2.17 on 2026-09-19 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cognito_sub", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mfa_activado", models.BooleanField(default=False)),
                ("nombre", models.CharField(blank=True, max_length=150)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "identidad",
                "verbose_name_plural": "identidades",
            },
        ),
    ]
