# Generated by Django 5.2.17 on 2026-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_useridentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="membership_dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
