/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["api_routers_health_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versiones del catálogo */
        get: operations["api_routers_catalog_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/measures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Medidas del Anexo II */
        get: operations["api_routers_catalog_measures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/measures/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una medida */
        get: operations["api_routers_catalog_measure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/applicability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Medidas aplicables a un sistema
         * @description Deriva medidas, refuerzos y selecciones pendientes. No guarda nada.
         */
        post: operations["api_routers_catalog_applicability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/dimensiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulario de categorías y niveles */
        get: operations["api_routers_catalog_dimensiones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Categorizar (sin cuenta)
         * @description Categoría y cifras. No guarda nada: es lo que responde el asistente de 5 pasos.
         */
        post: operations["api_routers_categorization_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pedir el PDF del resultado
         * @description Crea el informe y **encola** el PDF: el render no va en la petición web.
         */
        post: operations["api_routers_categorization_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del PDF */
        get: operations["api_routers_categorization_report_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report/{token}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar el PDF */
        get: operations["api_routers_categorization_report_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/vocabulario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dimensiones y niveles */
        get: operations["api_routers_categorization_vocabulario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sistemas de la organización */
        get: operations["api_routers_dda_systems"];
        put?: never;
        /** Dar de alta un sistema */
        post: operations["api_routers_dda_create_system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Guardar la categorización */
        put: operations["api_routers_dda_set_valuation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/dda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generar una versión de la DdA */
        post: operations["api_routers_dda_create_dda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una DdA */
        get: operations["api_routers_dda_get_dda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/measures/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar una medida de la DdA */
        patch: operations["api_routers_dda_patch_measure"];
        trace?: never;
    };
    "/api/dda/{dda_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar la DdA
         * @description Solo el RSEG, y solo si no quedan selecciones sin resolver ni no-aplicables sin justificar.
         */
        post: operations["api_routers_dda_approve_dda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/oscal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar la DdA en OSCAL (profile) */
        get: operations["api_routers_dda_export_oscal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encolar el PDF de la DdA */
        post: operations["api_routers_dda_queue_pdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Code */
            code: string;
            /** Oscal Version */
            oscal_version: string;
            /** Source Version */
            source_version: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Is Current */
            is_current: boolean;
            /** License */
            license: string;
            /** Source Url */
            source_url: string;
        };
        /** MeasureOut */
        MeasureOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
        };
        /** ItemOut */
        ItemOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Prose */
            prose: string;
        };
        /** MeasureDetailOut */
        MeasureDetailOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
            /** Overview */
            overview: string;
            /** Refuerzos */
            refuerzos: components["schemas"]["RefuerzoOut"][];
            /** Items */
            items: components["schemas"]["ItemOut"][];
        };
        /** RefuerzoOut */
        RefuerzoOut: {
            /** Code */
            code: string;
            /** Titulo */
            titulo: string;
            /** Opcional */
            opcional: boolean;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
        };
        /** AplicabilidadOut */
        AplicabilidadOut: {
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
            /** Total Aplicables */
            total_aplicables: number;
            /** Aplicables */
            aplicables: components["schemas"]["MedidaAplicableOut"][];
            /** No Aplicables */
            no_aplicables: [
                string,
                string
            ][];
            /** Selecciones Pendientes */
            selecciones_pendientes: components["schemas"]["SeleccionOut"][];
        };
        /** MedidaAplicableOut */
        MedidaAplicableOut: {
            /** Measure Id */
            measure_id: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Motivo */
            motivo: string;
            /** Refuerzos Obligatorios */
            refuerzos_obligatorios: string[];
            /** Refuerzos Opcionales */
            refuerzos_opcionales: string[];
            /** Refuerzos No Aplicables */
            refuerzos_no_aplicables: string[];
            /** Selecciones */
            selecciones: components["schemas"]["SeleccionOut"][];
        };
        /** SeleccionOut */
        SeleccionOut: {
            /** Param Id */
            param_id: string;
            /** Measure Id */
            measure_id: string;
            /** Nivel */
            nivel: string | null;
            /** Opciones */
            opciones: string[];
            /** Usage */
            usage: string;
        };
        /**
         * PerfilIn
         * @description Categoría y nivel por dimensión. Si no se da categoría, se deriva (Anexo I).
         */
        PerfilIn: {
            /** Categoria */
            categoria?: ("BASICA" | "MEDIA" | "ALTA") | null;
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
        };
        /** CategorizacionOut */
        CategorizacionOut: {
            /** Categoria */
            categoria: string;
            /** Sin Determinar */
            sin_determinar: boolean;
            /**
             * Aviso
             * @default
             */
            aviso: string;
            /** Madurez Minima */
            madurez_minima: number;
            /** Requiere Certificacion */
            requiere_certificacion: boolean;
            /** Dimensiones */
            dimensiones: components["schemas"]["DimensionOut"][];
            /** Resumen */
            resumen: {
                [key: string]: unknown;
            };
        };
        /** DimensionOut */
        DimensionOut: {
            /** Dim */
            dim: string;
            /** Nombre */
            nombre: string;
            /** Nivel */
            nivel: string;
            /** Marca Categoria */
            marca_categoria: boolean;
        };
        /** NivelesIn */
        NivelesIn: {
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
        };
        /** InformeOut */
        InformeOut: {
            /** Token */
            token: string;
            /** Categoria */
            categoria: string;
            /** Estado */
            estado: string;
            /** Descarga */
            descarga: string;
        };
        /** InformeIn */
        InformeIn: {
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * Organizacion
             * @default
             */
            organizacion: string;
            /**
             * Alcance
             * @default
             */
            alcance: string;
        };
        /** SystemOut */
        SystemOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
        };
        /** SystemIn */
        SystemIn: {
            /** Nombre */
            nombre: string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
        };
        /** ValoracionIn */
        ValoracionIn: {
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
        };
        /** DdaOut */
        DdaOut: {
            /** Id */
            id: number;
            /** Version */
            version: number;
            /** Estado */
            estado: string;
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
            /** Catalogo */
            catalogo: string;
            /** Madurez Minima */
            madurez_minima: number;
            /** Problemas */
            problemas: string[];
            /** Medidas */
            medidas: components["schemas"]["MedidaOut"][];
        };
        /** MedidaOut */
        MedidaOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplica */
            aplica: boolean;
            /** Motivo */
            motivo: string;
            /** Justificacion */
            justificacion: string;
            /** Compensatoria */
            compensatoria: string;
            /** Refuerzos Obligatorios */
            refuerzos_obligatorios: string[];
            /** Refuerzos Opcionales */
            refuerzos_opcionales: string[];
            /** Selecciones */
            selecciones: {
                [key: string]: string;
            };
        };
        /** DecisionIn */
        DecisionIn: {
            /** Aplica */
            aplica?: boolean | null;
            /** Justificacion */
            justificacion?: string | null;
            /** Compensatoria */
            compensatoria?: string | null;
            /** Selecciones */
            selecciones?: {
                [key: string]: string;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_routers_health_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    api_routers_catalog_versions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
        };
    };
    api_routers_catalog_measures: {
        parameters: {
            query?: {
                marco?: string | null;
                familia?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureOut"][];
                };
            };
        };
    };
    api_routers_catalog_measure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureDetailOut"];
                };
            };
        };
    };
    api_routers_catalog_applicability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerfilIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AplicabilidadOut"];
                };
            };
        };
    };
    api_routers_catalog_dimensiones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_categorization_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NivelesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizacionOut"];
                };
            };
        };
    };
    api_routers_categorization_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InformeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeOut"];
                };
            };
        };
    };
    api_routers_categorization_report_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeOut"];
                };
            };
        };
    };
    api_routers_categorization_report_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_categorization_vocabulario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_dda_systems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"][];
                };
            };
        };
    };
    api_routers_dda_create_system: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    api_routers_dda_set_valuation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValoracionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    api_routers_dda_create_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_get_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_patch_measure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedidaOut"];
                };
            };
        };
    };
    api_routers_dda_approve_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_export_oscal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_dda_queue_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
