/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["api_routers_health_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear cuenta
         * @description Crea la organización, su propietario y su primer sistema, en una transacción.
         *
         *     Si trae el token de una categorización anónima vigente, el sistema nace con sus
         *     niveles por dimensión. Si caducó, el alta **no** se bloquea: se avisa.
         */
        post: operations["api_routers_auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar el correo */
        post: operations["api_routers_auth_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reenviar el código */
        post: operations["api_routers_auth_resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión */
        post: operations["api_routers_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segundo factor */
        post: operations["api_routers_auth_mfa_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refrescar la sesión */
        post: operations["api_routers_auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión */
        post: operations["api_routers_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quién soy */
        get: operations["api_routers_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Olvidé la contraseña */
        post: operations["api_routers_auth_password_forgot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nueva contraseña */
        post: operations["api_routers_auth_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Empezar el alta del segundo factor */
        post: operations["api_routers_auth_mfa_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar el segundo factor */
        post: operations["api_routers_auth_mfa_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invitation/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver la invitación */
        get: operations["api_routers_auth_invitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invitation/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aceptar la invitación */
        post: operations["api_routers_auth_invitation_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Miembros de la organización */
        get: operations["api_routers_members_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitaciones pendientes */
        get: operations["api_routers_members_invitations"];
        put?: never;
        /** Invitar a alguien */
        post: operations["api_routers_members_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/invitations/{invitacion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocar la invitación */
        delete: operations["api_routers_members_invitation_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{membresia_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar el rol */
        patch: operations["api_routers_members_member_update"];
        trace?: never;
    };
    "/api/members/{membresia_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revocar el acceso */
        post: operations["api_routers_members_member_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{membresia_id}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transferir la propiedad */
        post: operations["api_routers_members_member_transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{membresia_id}/reset-mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restablecer el segundo factor
         * @description Para quien ha perdido el móvil. Cognito no da códigos de recuperación (D1).
         */
        post: operations["api_routers_members_member_reset_mfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mi actividad
         * @description Lo que ha hecho quien llama. El registro encadenado, útil para su dueño y no solo
         *     para el auditor (`docs/roles_y_permisos.md` §5).
         */
        get: operations["api_routers_members_my_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versiones del catálogo */
        get: operations["api_routers_catalog_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/measures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Medidas del Anexo II */
        get: operations["api_routers_catalog_measures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/measures/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una medida */
        get: operations["api_routers_catalog_measure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/applicability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Medidas aplicables a un sistema
         * @description Deriva medidas, refuerzos y selecciones pendientes. No guarda nada.
         */
        post: operations["api_routers_catalog_applicability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/dimensiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulario de categorías y niveles */
        get: operations["api_routers_catalog_dimensiones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Categorizar (sin cuenta)
         * @description Categoría y cifras. No guarda nada: es lo que responde el asistente de 5 pasos.
         */
        post: operations["api_routers_categorization_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pedir el PDF del resultado
         * @description Crea el informe y **encola** el PDF: el render no va en la petición web.
         */
        post: operations["api_routers_categorization_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del PDF */
        get: operations["api_routers_categorization_report_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/report/{token}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar el PDF */
        get: operations["api_routers_categorization_report_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization/vocabulario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dimensiones y niveles */
        get: operations["api_routers_categorization_vocabulario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sistemas de la organización */
        get: operations["api_routers_dda_systems"];
        put?: never;
        /** Dar de alta un sistema */
        post: operations["api_routers_dda_create_system"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Guardar la categorización */
        put: operations["api_routers_dda_set_valuation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/dda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generar una versión de la DdA */
        post: operations["api_routers_dda_create_dda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una DdA */
        get: operations["api_routers_dda_get_dda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/measures/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar una medida de la DdA */
        patch: operations["api_routers_dda_patch_measure"];
        trace?: never;
    };
    "/api/dda/{dda_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar la DdA
         * @description Solo el RSEG, y solo si no quedan selecciones sin resolver ni no-aplicables sin justificar.
         */
        post: operations["api_routers_dda_approve_dda"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/oscal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar la DdA en OSCAL (profile) */
        get: operations["api_routers_dda_export_oscal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dda/{dda_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encolar el PDF de la DdA */
        post: operations["api_routers_dda_queue_pdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Checklist de medidas (M4)
         * @description Devuelve la tabla completa con sus índices ya calculados.
         *
         *     Crea de paso las filas de madurez que falten: el cliente tiene que poder asignar
         *     responsable y fecha a una medida antes de haber declarado ningún nivel.
         */
        get: operations["api_routers_checklist_checklist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/checklist/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar la madurez de una medida
         * @description Guarda el cambio y encola el recálculo del riesgo.
         *
         *     Es el paso único del criterio de cierre de la fase: una madurez cambia y con ella
         *     cambian el índice de cumplimiento (que se devuelve aquí mismo, recalculado) y el
         *     riesgo residual (que se rehace en Celery, porque recorre el grafo entero).
         */
        patch: operations["api_routers_checklist_patch_medida"];
        trace?: never;
    };
    "/api/systems/{system_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventario de activos */
        get: operations["api_routers_risk_activos"];
        put?: never;
        /** Dar de alta un activo */
        post: operations["api_routers_risk_crear_activo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Valorar un activo (0 a 10) */
        put: operations["api_routers_risk_valorar_activo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grafo de dependencias */
        get: operations["api_routers_risk_dependencias"];
        put?: never;
        /**
         * Declarar que un activo depende de otro
         * @description `parent` depende de `child`: el valor desciende del primero al segundo.
         *
         *     El ciclo no se rechaza aquí sino al recalcular, donde se puede nombrar entero. Lo
         *     que sí se rechaza de entrada es lo que no tiene arreglo: depender de uno mismo o de
         *     un activo de otro sistema.
         */
        post: operations["api_routers_risk_crear_dependencia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dependencies/{dependency_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Quitar una dependencia */
        delete: operations["api_routers_risk_borrar_dependencia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Riesgos del sistema, de mayor a menor residual */
        get: operations["api_routers_risk_riesgos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Añadir o ajustar amenaza */
        post: operations["api_routers_risk_amenaza"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{system_id}/risks/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalcular el riesgo (en segundo plano)
         * @description Encola el recálculo. Recorre el grafo entero: no va en la petición (§15).
         */
        post: operations["api_routers_risk_recalcular"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risks/{risk_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ¿Qué habría que subir para llegar ahí? */
        post: operations["api_routers_risk_simular"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risks/{risk_id}/treatment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Decidir qué se hace
         * @description Aceptar un riesgo es una decisión de dirección, no un valor por defecto.
         *
         *     Por eso `riesgo.aceptar` es una acción propia en la matriz y queda registrado quién
         *     lo acepta y cuándo: es lo primero que mira un auditor ante un riesgo alto asumido.
         */
        put: operations["api_routers_risk_tratamiento"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
        };
        /** RegistroOut */
        RegistroOut: {
            /** Email */
            email: string;
            /** Organizacion */
            organizacion: string;
            /** System Id */
            system_id: number;
            /**
             * Aviso
             * @default
             */
            aviso: string;
        };
        /** RegistroIn */
        RegistroIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Organizacion */
            organizacion: string;
            /**
             * Nombre
             * @default
             */
            nombre: string;
            /**
             * Nombre Sistema
             * @default
             */
            nombre_sistema: string;
            /**
             * Informe Token
             * @default
             */
            informe_token: string;
        };
        /** OkOut */
        OkOut: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Mensaje
             * @default
             */
            mensaje: string;
        };
        /** ConfirmarIn */
        ConfirmarIn: {
            /** Email */
            email: string;
            /** Codigo */
            codigo: string;
        };
        /** EmailIn */
        EmailIn: {
            /** Email */
            email: string;
        };
        /** SesionOut */
        SesionOut: {
            /**
             * Mfa Requerido
             * @default false
             */
            mfa_requerido: boolean;
            /**
             * Sesion
             * @default
             */
            sesion: string;
            /**
             * Email
             * @default
             */
            email: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MfaLoginIn */
        MfaLoginIn: {
            /** Email */
            email: string;
            /** Codigo */
            codigo: string;
            /** Sesion */
            sesion: string;
        };
        /** MembresiaOut */
        MembresiaOut: {
            /** Tenant Id */
            tenant_id: number;
            /** Organizacion */
            organizacion: string;
            /** Role */
            role: string;
            /** Role Nombre */
            role_nombre: string;
            /** Estado */
            estado: string;
            /**
             * Expires At
             * @default
             */
            expires_at: string;
            /**
             * Systems
             * @default []
             */
            systems: number[];
            /**
             * Bloques
             * @default []
             */
            bloques: string[];
        };
        /** YoOut */
        YoOut: {
            /** Email */
            email: string;
            /** Nombre */
            nombre: string;
            /** Mfa Activado */
            mfa_activado: boolean;
            /** Mfa Pendiente */
            mfa_pendiente: boolean;
            /** Membresias */
            membresias: components["schemas"]["MembresiaOut"][];
        };
        /** PasswordResetIn */
        PasswordResetIn: {
            /** Email */
            email: string;
            /** Codigo */
            codigo: string;
            /** Password */
            password: string;
        };
        /** MfaSetupOut */
        MfaSetupOut: {
            /** Secreto */
            secreto: string;
            /** Otpauth Uri */
            otpauth_uri: string;
            /** Aviso */
            aviso: string;
        };
        /** CodigoIn */
        CodigoIn: {
            /** Codigo */
            codigo: string;
        };
        /** InvitacionOut */
        InvitacionOut: {
            /** Organizacion */
            organizacion: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Role Nombre */
            role_nombre: string;
            /**
             * Invitado Por
             * @default
             */
            invitado_por: string;
            /** Caduca */
            caduca: string;
            /** Tiene Cuenta */
            tiene_cuenta: boolean;
        };
        /** AceptadaOut */
        AceptadaOut: {
            /** Organizacion */
            organizacion: string;
            /** Role */
            role: string;
            /** Email */
            email: string;
        };
        /** AceptarIn */
        AceptarIn: {
            /**
             * Password
             * @default
             */
            password: string;
            /**
             * Nombre
             * @default
             */
            nombre: string;
        };
        /** MiembroOut */
        MiembroOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Nombre
             * @default
             */
            nombre: string;
            /** Role */
            role: string;
            /** Role Nombre */
            role_nombre: string;
            /** Estado */
            estado: string;
            /**
             * Expires At
             * @default
             */
            expires_at: string;
            /**
             * Caducada
             * @default false
             */
            caducada: boolean;
            /**
             * Mfa Activado
             * @default false
             */
            mfa_activado: boolean;
            /**
             * Systems
             * @default []
             */
            systems: number[];
            /**
             * Bloques
             * @default []
             */
            bloques: string[];
        };
        /** InvitacionEmitidaOut */
        InvitacionEmitidaOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Caduca */
            caduca: string;
            /** Enlace */
            enlace: string;
        };
        /** InvitacionIn */
        InvitacionIn: {
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Systems
             * @default []
             */
            systems: number[];
            /**
             * Bloques
             * @default []
             */
            bloques: string[];
            /** Membership Dias */
            membership_dias?: number | null;
        };
        /** InvitacionPendienteOut */
        InvitacionPendienteOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Role Nombre */
            role_nombre: string;
            /** Caduca */
            caduca: string;
        };
        /** CambioRolIn */
        CambioRolIn: {
            /** Role */
            role: string;
            /** Dias */
            dias?: number | null;
        };
        /** ReiniciarMfaOut */
        ReiniciarMfaOut: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Mensaje */
            mensaje: string;
        };
        /** ActividadOut */
        ActividadOut: {
            /** Fecha */
            fecha: string;
            /** Accion */
            accion: string;
            /**
             * Objeto
             * @default
             */
            objeto: string;
            /**
             * Datos
             * @default {}
             */
            datos: {
                [key: string]: unknown;
            };
        };
        /** VersionOut */
        VersionOut: {
            /** Code */
            code: string;
            /** Oscal Version */
            oscal_version: string;
            /** Source Version */
            source_version: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Is Current */
            is_current: boolean;
            /** License */
            license: string;
            /** Source Url */
            source_url: string;
        };
        /** MeasureOut */
        MeasureOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
        };
        /** ItemOut */
        ItemOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Prose */
            prose: string;
        };
        /** MeasureDetailOut */
        MeasureDetailOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
            /** Overview */
            overview: string;
            /** Refuerzos */
            refuerzos: components["schemas"]["RefuerzoOut"][];
            /** Items */
            items: components["schemas"]["ItemOut"][];
        };
        /** RefuerzoOut */
        RefuerzoOut: {
            /** Code */
            code: string;
            /** Titulo */
            titulo: string;
            /** Opcional */
            opcional: boolean;
            /** Aplicacion Por */
            aplicacion_por: string;
            /** Categorias */
            categorias: string[];
            /** Niveles */
            niveles: string[];
            /** Dimensiones */
            dimensiones: string[];
        };
        /** AplicabilidadOut */
        AplicabilidadOut: {
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
            /** Total Aplicables */
            total_aplicables: number;
            /** Aplicables */
            aplicables: components["schemas"]["MedidaAplicableOut"][];
            /** No Aplicables */
            no_aplicables: [
                string,
                string
            ][];
            /** Selecciones Pendientes */
            selecciones_pendientes: components["schemas"]["SeleccionOut"][];
        };
        /** MedidaAplicableOut */
        MedidaAplicableOut: {
            /** Measure Id */
            measure_id: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Motivo */
            motivo: string;
            /** Refuerzos Obligatorios */
            refuerzos_obligatorios: string[];
            /** Refuerzos Opcionales */
            refuerzos_opcionales: string[];
            /** Refuerzos No Aplicables */
            refuerzos_no_aplicables: string[];
            /** Selecciones */
            selecciones: components["schemas"]["SeleccionOut"][];
        };
        /** SeleccionOut */
        SeleccionOut: {
            /** Param Id */
            param_id: string;
            /** Measure Id */
            measure_id: string;
            /** Nivel */
            nivel: string | null;
            /** Opciones */
            opciones: string[];
            /** Usage */
            usage: string;
        };
        /**
         * PerfilIn
         * @description Categoría y nivel por dimensión. Si no se da categoría, se deriva (Anexo I).
         */
        PerfilIn: {
            /** Categoria */
            categoria?: ("BASICA" | "MEDIA" | "ALTA") | null;
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
        };
        /** CategorizacionOut */
        CategorizacionOut: {
            /** Categoria */
            categoria: string;
            /** Sin Determinar */
            sin_determinar: boolean;
            /**
             * Aviso
             * @default
             */
            aviso: string;
            /** Madurez Minima */
            madurez_minima: number;
            /** Requiere Certificacion */
            requiere_certificacion: boolean;
            /** Dimensiones */
            dimensiones: components["schemas"]["DimensionOut"][];
            /** Resumen */
            resumen: {
                [key: string]: unknown;
            };
        };
        /** DimensionOut */
        DimensionOut: {
            /** Dim */
            dim: string;
            /** Nombre */
            nombre: string;
            /** Nivel */
            nivel: string;
            /** Marca Categoria */
            marca_categoria: boolean;
        };
        /** NivelesIn */
        NivelesIn: {
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
        };
        /** InformeOut */
        InformeOut: {
            /** Token */
            token: string;
            /** Categoria */
            categoria: string;
            /** Estado */
            estado: string;
            /** Descarga */
            descarga: string;
        };
        /** InformeIn */
        InformeIn: {
            /**
             * C
             * @default NA
             * @enum {string}
             */
            C: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * I
             * @default NA
             * @enum {string}
             */
            I: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * T
             * @default NA
             * @enum {string}
             */
            T: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * A
             * @default NA
             * @enum {string}
             */
            A: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * D
             * @default NA
             * @enum {string}
             */
            D: "NA" | "BAJO" | "MEDIO" | "ALTO";
            /**
             * Organizacion
             * @default
             */
            organizacion: string;
            /**
             * Alcance
             * @default
             */
            alcance: string;
        };
        /** SystemOut */
        SystemOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
        };
        /** SystemIn */
        SystemIn: {
            /** Nombre */
            nombre: string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
        };
        /**
         * ValoracionIn
         * @description Lo que se puede editar en línea. Lo que no se manda, no se toca.
         */
        ValoracionIn: {
            /** Maturity Level */
            maturity_level?: number | null;
            /** Objetivo */
            objetivo?: number | null;
            /** Applies */
            applies?: boolean | null;
            /** Responsable Id */
            responsable_id?: number | null;
            /** Fecha Limite */
            fecha_limite?: string | null;
            /** Notas */
            notas?: string | null;
            /** Limpiar */
            limpiar?: string[] | null;
        };
        /** DdaOut */
        DdaOut: {
            /** Id */
            id: number;
            /** Version */
            version: number;
            /** Estado */
            estado: string;
            /** Categoria */
            categoria: string;
            /** Niveles */
            niveles: {
                [key: string]: string;
            };
            /** Catalogo */
            catalogo: string;
            /** Madurez Minima */
            madurez_minima: number;
            /** Problemas */
            problemas: string[];
            /** Medidas */
            medidas: components["schemas"]["MedidaOut"][];
        };
        /** MedidaOut */
        MedidaOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplica */
            aplica: boolean;
            /** Motivo */
            motivo: string;
            /** Justificacion */
            justificacion: string;
            /** Compensatoria */
            compensatoria: string;
            /** Refuerzos Obligatorios */
            refuerzos_obligatorios: string[];
            /** Refuerzos Opcionales */
            refuerzos_opcionales: string[];
            /** Selecciones */
            selecciones: {
                [key: string]: string;
            };
        };
        /** DecisionIn */
        DecisionIn: {
            /** Aplica */
            aplica?: boolean | null;
            /** Justificacion */
            justificacion?: string | null;
            /** Compensatoria */
            compensatoria?: string | null;
            /** Selecciones */
            selecciones?: {
                [key: string]: string;
            } | null;
        };
        /** ChecklistOut */
        ChecklistOut: {
            /** System Id */
            system_id: number;
            /** Sistema */
            sistema: string;
            /** Categoria */
            categoria: string;
            /** Objetivo Categoria */
            objetivo_categoria: number;
            /** Escala */
            escala: {
                [key: string]: string;
            };
            /** Medidas */
            medidas: components["schemas"]["FilaOut"][];
            sistema_indice: components["schemas"]["IndiceOut"];
            /** Por Marco */
            por_marco: {
                [key: string]: components["schemas"]["IndiceOut"];
            };
            /** Por Familia */
            por_familia: {
                [key: string]: components["schemas"]["IndiceOut"];
            };
            /** Brechas */
            brechas: string[];
        };
        /**
         * FilaOut
         * @description Una fila del checklist: lo que el cliente declara y lo que eso vale.
         */
        FilaOut: {
            /** Code */
            code: string;
            /** Nombre */
            nombre: string;
            /** Marco */
            marco: string;
            /** Familia */
            familia: string;
            /** Aplica */
            aplica: boolean;
            /** Motivo */
            motivo: string;
            /** Madurez */
            madurez: number | null;
            /** Objetivo */
            objetivo: number;
            /** Delta */
            delta: number | null;
            /** Semaforo */
            semaforo: string;
            /** Madurez Pct */
            madurez_pct: number;
            /** Cumplimiento Pct */
            cumplimiento_pct: number;
            /** No Soportada */
            no_soportada: boolean;
            /** Responsable */
            responsable: string;
            /** Responsable Id */
            responsable_id: number | null;
            /** Fecha Limite */
            fecha_limite: string | null;
            /** Notas */
            notas: string;
        };
        /** IndiceOut */
        IndiceOut: {
            /** Clave */
            clave: string;
            /** Medidas */
            medidas: number;
            /** Con Datos */
            con_datos: number;
            /** En Objetivo */
            en_objetivo: number;
            /** No Soportadas */
            no_soportadas: number;
            /** Madurez */
            madurez: number;
            /** Cumplimiento */
            cumplimiento: number;
            /** Madurez Media */
            madurez_media: number;
            /** Peor */
            peor: string | null;
        };
        /** ActivoOut */
        ActivoOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Tipo */
            tipo: string;
            /** Tipo Nombre */
            tipo_nombre: string;
            /** Terminal */
            terminal: boolean;
            /** Valores */
            valores: {
                [key: string]: number;
            };
        };
        /** ActivoIn */
        ActivoIn: {
            /** Nombre */
            nombre: string;
            /** Tipo */
            tipo: string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
            /**
             * Valores
             * @default {}
             */
            valores: {
                [key: string]: number;
            };
            /**
             * Proponer Amenazas
             * @default true
             */
            proponer_amenazas: boolean;
        };
        /** ValoresIn */
        ValoresIn: {
            /** Valores */
            valores: {
                [key: string]: number;
            };
        };
        /** DependenciaOut */
        DependenciaOut: {
            /** Id */
            id: number;
            /** Parent */
            parent: number;
            /** Child */
            child: number;
            /** Degree */
            degree: number;
        };
        /** DependenciaIn */
        DependenciaIn: {
            /** Parent */
            parent: number;
            /** Child */
            child: number;
            /**
             * Degree
             * @default 1
             */
            degree: number;
        };
        /** RiesgoOut */
        RiesgoOut: {
            /** Id */
            id: number;
            /** Asset Id */
            asset_id: number;
            /** Activo */
            activo: string;
            /** Threat */
            threat: string;
            /** Amenaza */
            amenaza: string;
            /** Dim */
            dim: string;
            /** Frequency */
            frequency: number;
            /** Degradation */
            degradation: number;
            /** Valor Acumulado */
            valor_acumulado: number | null;
            /** Riesgo Intrinseco */
            riesgo_intrinseco: number | null;
            /** Riesgo Residual */
            riesgo_residual: number | null;
            /** Calculado En */
            calculado_en: string | null;
            /** Salvaguardas */
            salvaguardas: components["schemas"]["SalvaguardaOut"][];
            /** Decision */
            decision: string;
            /** Riesgo Objetivo */
            riesgo_objetivo: number | null;
        };
        /** SalvaguardaOut */
        SalvaguardaOut: {
            /** Measure */
            measure: string;
            /** Aspect */
            aspect: string;
            /** Weight */
            weight: number;
            /** Nivel */
            nivel: number;
            /** Eficacia */
            eficacia: number;
            /** Soportada */
            soportada: boolean;
        };
        /** AmenazaIn */
        AmenazaIn: {
            /** Threat */
            threat: string;
            /** Dim */
            dim: string;
            /** Frequency */
            frequency: number;
            /** Degradation */
            degradation: number;
            /**
             * Notas
             * @default
             */
            notas: string;
        };
        /** SimulacionIn */
        SimulacionIn: {
            /** Objetivo */
            objetivo: number;
        };
        /** TratamientoIn */
        TratamientoIn: {
            /** Decision */
            decision: string;
            /** Target Risk */
            target_risk?: number | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_routers_health_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    api_routers_auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroOut"];
                };
            };
        };
    };
    api_routers_auth_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmarIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_resend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
        };
    };
    api_routers_auth_mfa_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaLoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
        };
    };
    api_routers_auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
        };
    };
    api_routers_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YoOut"];
                };
            };
        };
    };
    api_routers_auth_password_forgot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_mfa_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupOut"];
                };
            };
        };
    };
    api_routers_auth_mfa_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodigoIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOut"];
                };
            };
        };
    };
    api_routers_auth_invitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitacionOut"];
                };
            };
        };
    };
    api_routers_auth_invitation_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AceptarIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AceptadaOut"];
                };
            };
        };
    };
    api_routers_members_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroOut"][];
                };
            };
        };
    };
    api_routers_members_invitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitacionPendienteOut"][];
                };
            };
        };
    };
    api_routers_members_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitacionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitacionEmitidaOut"];
                };
            };
        };
    };
    api_routers_members_invitation_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitacion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_members_member_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membresia_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioRolIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroOut"];
                };
            };
        };
    };
    api_routers_members_member_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membresia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroOut"];
                };
            };
        };
    };
    api_routers_members_member_transfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membresia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroOut"];
                };
            };
        };
    };
    api_routers_members_member_reset_mfa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membresia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReiniciarMfaOut"];
                };
            };
        };
    };
    api_routers_members_my_activity: {
        parameters: {
            query?: {
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActividadOut"][];
                };
            };
        };
    };
    api_routers_catalog_versions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
        };
    };
    api_routers_catalog_measures: {
        parameters: {
            query?: {
                marco?: string | null;
                familia?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureOut"][];
                };
            };
        };
    };
    api_routers_catalog_measure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureDetailOut"];
                };
            };
        };
    };
    api_routers_catalog_applicability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerfilIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AplicabilidadOut"];
                };
            };
        };
    };
    api_routers_catalog_dimensiones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_categorization_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NivelesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizacionOut"];
                };
            };
        };
    };
    api_routers_categorization_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InformeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeOut"];
                };
            };
        };
    };
    api_routers_categorization_report_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeOut"];
                };
            };
        };
    };
    api_routers_categorization_report_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_categorization_vocabulario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_dda_systems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"][];
                };
            };
        };
    };
    api_routers_dda_create_system: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    api_routers_dda_set_valuation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValoracionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    api_routers_dda_create_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_get_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_patch_measure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedidaOut"];
                };
            };
        };
    };
    api_routers_dda_approve_dda: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdaOut"];
                };
            };
        };
    };
    api_routers_dda_export_oscal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_dda_queue_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dda_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_checklist_checklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistOut"];
                };
            };
        };
    };
    api_routers_checklist_patch_medida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValoracionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistOut"];
                };
            };
        };
    };
    api_routers_risk_activos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoOut"][];
                };
            };
        };
    };
    api_routers_risk_crear_activo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivoIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoOut"];
                };
            };
        };
    };
    api_routers_risk_valorar_activo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValoresIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoOut"];
                };
            };
        };
    };
    api_routers_risk_dependencias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependenciaOut"][];
                };
            };
        };
    };
    api_routers_risk_crear_dependencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DependenciaIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependenciaOut"];
                };
            };
        };
    };
    api_routers_risk_borrar_dependencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dependency_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_risk_riesgos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiesgoOut"][];
                };
            };
        };
    };
    api_routers_risk_amenaza: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmenazaIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiesgoOut"];
                };
            };
        };
    };
    api_routers_risk_recalcular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_risk_simular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulacionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_risk_tratamiento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TratamientoIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiesgoOut"];
                };
            };
        };
    };
}
