# Generated by Django 5.2.17 on 2026-09-19 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_maturityeffectiveness_mageritthreat_and_more"),
        ("compliance", "0004_measureassessment"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activos",
                        to="catalog.mageritassettype",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activos",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "activo",
                "verbose_name_plural": "activos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AssetDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("degree", models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soporta",
                        to="risk.asset",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depende_de",
                        to="risk.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "dependencia",
                "verbose_name_plural": "dependencias",
            },
        ),
        migrations.CreateModel(
            name="AssetValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dim",
                    models.CharField(
                        choices=[("C", "C"), ("I", "I"), ("T", "T"), ("A", "A"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("own_value", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("justificacion", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="risk.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "valoración de activo",
                "verbose_name_plural": "valoraciones de activos",
            },
        ),
        migrations.CreateModel(
            name="ThreatInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dim", models.CharField(max_length=1)),
                ("frequency", models.DecimalField(decimal_places=3, max_digits=7)),
                ("degradation", models.DecimalField(decimal_places=3, max_digits=4)),
                ("notas", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenazas",
                        to="risk.asset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.mageritthreat"
                    ),
                ),
            ],
            options={
                "verbose_name": "amenaza sobre activo",
                "verbose_name_plural": "amenazas sobre activos",
                "ordering": ["asset__nombre", "threat__orden", "dim"],
            },
        ),
        migrations.CreateModel(
            name="RiskTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MITIGAR", "Reducir"),
                            ("ACEPTAR", "Aceptar"),
                            ("TRANSFERIR", "Transferir"),
                            ("EVITAR", "Evitar"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "target_risk",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("aceptado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "aceptado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="riesgos_aceptados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="riesgos_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "threat_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tratamiento",
                        to="risk.threatinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "tratamiento del riesgo",
                "verbose_name_plural": "tratamientos del riesgo",
            },
        ),
        migrations.CreateModel(
            name="RiskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accumulated_value", models.DecimalField(decimal_places=4, max_digits=8)),
                ("intrinsic_risk", models.DecimalField(decimal_places=4, max_digits=12)),
                ("residual_freq_factor", models.DecimalField(decimal_places=6, max_digits=8)),
                ("residual_impact_factor", models.DecimalField(decimal_places=6, max_digits=8)),
                ("residual_risk", models.DecimalField(decimal_places=4, max_digits=12)),
                ("salvaguardas", models.JSONField(blank=True, default=list)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="risk.threatinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de riesgo",
                "verbose_name_plural": "resultados de riesgo",
                "ordering": ["-residual_risk"],
            },
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("system", "nombre"), name="uniq_activo_por_sistema"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetdependency",
            constraint=models.UniqueConstraint(fields=("parent", "child"), name="uniq_dependencia"),
        ),
        migrations.AddConstraint(
            model_name="assetdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("child")), _negated=True),
                name="dependencia_no_refleja",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(("degree__gt", 0), ("degree__lte", 1)),
                name="grado_de_dependencia_entre_0_y_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetvaluation",
            constraint=models.UniqueConstraint(
                fields=("asset", "dim"), name="uniq_valoracion_activo_dim"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("own_value__gte", 0), ("own_value__lte", 10)),
                name="valor_de_activo_entre_0_y_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatinstance",
            constraint=models.UniqueConstraint(
                fields=("asset", "threat", "dim"), name="uniq_amenaza_por_activo_dim"
            ),
        ),
        migrations.AddConstraint(
            model_name="threatinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(("degradation__gte", 0), ("degradation__lte", 1)),
                name="degradacion_entre_0_y_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__gte", 0)), name="frecuencia_no_negativa"
            ),
        ),
    ]
