# Generated by Django 5.2.17 on 2026-09-19 21:58

import apps.evidence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_evidencetemplate_enscheck_productevidencehint_and_more"),
        ("compliance", "0004_measureassessment"),
        ("tenancy", "0003_invitation_membership_dias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APORTADA", "Aportada, sin validar"),
                            ("VALIDADA", "Validada"),
                            ("CADUCADA", "Caducada"),
                            ("FUERA_DE_ALCANCE", "Fuera de alcance"),
                            ("NO_APLICA_JUSTIFICADO", "No aplica, justificado"),
                        ],
                        default="PENDIENTE",
                        max_length=25,
                    ),
                ),
                ("origen", models.JSONField(blank=True, default=dict)),
                ("motivo", models.CharField(blank=True, max_length=400)),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                ("proxima_renovacion", models.DateField(blank=True, null=True)),
                ("justificacion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidencias_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos_evidencia",
                        to="compliance.system",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos",
                        to="catalog.evidencetemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "requisito de evidencia",
                "verbose_name_plural": "requisitos de evidencia",
                "ordering": ["template__measure__orden", "template__preferencia", "template__code"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=300)),
                (
                    "fichero",
                    models.FileField(blank=True, upload_to=apps.evidence.models.ruta_evidencia),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=300)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("tamano", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("fecha_evidencia", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("APORTADA", "Aportada"),
                            ("EN_REVISION", "En revisión"),
                            ("VALIDADA", "Validada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CADUCADA", "Caducada"),
                        ],
                        default="APORTADA",
                        max_length=12,
                    ),
                ),
                ("criterios_marcados", models.JSONField(blank=True, default=list)),
                ("notas", models.TextField(blank=True)),
                ("revisado_en", models.DateTimeField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("excepcion_separacion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aportada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidencias_aportadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisitos",
                    models.ManyToManyField(
                        blank=True, related_name="evidencias", to="evidence.evidencerequirement"
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidencias_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ["-fecha_evidencia", "-creado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="evidencerequirement",
            constraint=models.UniqueConstraint(
                fields=("system", "template"), name="uniq_requisito_por_plantilla"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "NO_APLICA_JUSTIFICADO"), _negated=True),
                    models.Q(("justificacion", ""), _negated=True),
                    _connector="OR",
                ),
                name="no_aplica_exige_justificacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "RECHAZADA"), _negated=True),
                    models.Q(("motivo_rechazo", ""), _negated=True),
                    _connector="OR",
                ),
                name="rechazo_exige_motivo",
            ),
        ),
    ]
