# Generated by Django 5.2.17 on 2026-09-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=60, unique=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(default=False)),
                ("oscal_version", models.CharField(max_length=20)),
                ("source_version", models.CharField(max_length=40)),
                ("source_last_modified", models.CharField(blank=True, max_length=40)),
                ("source_url", models.URLField(blank=True)),
                ("license", models.CharField(default="EUPL-1.2", max_length=40)),
                ("source_sha256", models.CharField(max_length=64)),
                ("source_path", models.CharField(blank=True, max_length=300)),
                ("source_s3_key", models.CharField(blank=True, max_length=300)),
                ("blens_layer_version", models.CharField(blank=True, max_length=40)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "versión del catálogo",
                "verbose_name_plural": "versiones del catálogo",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="EnsMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                (
                    "marco",
                    models.CharField(
                        choices=[
                            ("org", "Marco organizativo"),
                            ("op", "Marco operacional"),
                            ("mp", "Medidas de protección"),
                        ],
                        max_length=5,
                    ),
                ),
                ("familia", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=300)),
                ("overview", models.TextField(blank=True)),
                ("aplicacion_por", models.CharField(blank=True, max_length=20)),
                ("categorias", models.JSONField(blank=True, default=list)),
                ("niveles", models.JSONField(blank=True, default=list)),
                ("dimensiones", models.JSONField(blank=True, default=list)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="catalog.catalogversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "medida",
                "verbose_name_plural": "medidas",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EnsRefuerzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=300)),
                ("aplicacion_por", models.CharField(blank=True, max_length=20)),
                ("categorias", models.JSONField(blank=True, default=list)),
                ("niveles", models.JSONField(blank=True, default=list)),
                ("dimensiones", models.JSONField(blank=True, default=list)),
                ("opcional", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refuerzos",
                        to="catalog.ensmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "refuerzo",
                "verbose_name_plural": "refuerzos",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EnsRequirementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("label", models.CharField(blank=True, max_length=40)),
                ("prose", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.ensmeasure",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.ensrequirementitem",
                    ),
                ),
                (
                    "refuerzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.ensrefuerzo",
                    ),
                ),
            ],
            options={
                "verbose_name": "requisito",
                "verbose_name_plural": "requisitos",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EnsSelectionParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("usage", models.CharField(blank=True, max_length=300)),
                ("categoria", models.CharField(blank=True, max_length=10)),
                ("nivel", models.CharField(blank=True, max_length=10)),
                ("choices", models.JSONField(default=list)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="catalog.ensmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "selección de refuerzo",
                "verbose_name_plural": "selecciones de refuerzo",
            },
        ),
        migrations.AddConstraint(
            model_name="ensmeasure",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_measure_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="ensrefuerzo",
            constraint=models.UniqueConstraint(
                fields=("measure", "code"), name="uniq_refuerzo_por_medida"
            ),
        ),
        migrations.AddIndex(
            model_name="ensrequirementitem",
            index=models.Index(fields=["label"], name="catalog_ens_label_875343_idx"),
        ),
        migrations.AddConstraint(
            model_name="ensrequirementitem",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_item_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="ensselectionparam",
            constraint=models.UniqueConstraint(
                fields=("measure", "code"), name="uniq_param_por_medida"
            ),
        ),
    ]
