# Generated by Django 5.2.17 on 2026-09-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaturityEffectiveness",
            fields=[
                ("level", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=40)),
                ("effectiveness", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                "verbose_name": "eficacia por madurez",
                "verbose_name_plural": "eficacias por madurez",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="MageritThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NATURAL", "Desastres naturales"),
                            ("INDUSTRIAL", "De origen industrial"),
                            ("ERROR", "Errores y fallos no intencionados"),
                            ("ATAQUE", "Ataques intencionados"),
                        ],
                        max_length=12,
                    ),
                ),
                ("dims", models.JSONField(default=list)),
                ("aplica_a", models.JSONField(blank=True, default=list)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="catalog.catalogversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "amenaza",
                "verbose_name_plural": "amenazas",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="MageritThreatDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dim", models.CharField(max_length=1)),
                ("default_degradation", models.DecimalField(decimal_places=3, max_digits=4)),
                ("default_frequency", models.DecimalField(decimal_places=3, max_digits=7)),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores_por_defecto",
                        to="catalog.mageritthreat",
                    ),
                ),
            ],
            options={
                "verbose_name": "valor por defecto de amenaza",
                "verbose_name_plural": "valores por defecto de amenazas",
            },
        ),
        migrations.CreateModel(
            name="MeasureThreatMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dim", models.CharField(blank=True, max_length=1)),
                (
                    "aspect",
                    models.CharField(
                        choices=[("FREQ", "Reduce la probabilidad"), ("IMPACT", "Reduce el daño")],
                        max_length=6,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_threat_map",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salvaguarda_de",
                        to="catalog.ensmeasure",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salvaguardas",
                        to="catalog.mageritthreat",
                    ),
                ),
            ],
            options={
                "verbose_name": "salvaguarda",
                "verbose_name_plural": "mapa medida-amenaza",
                "ordering": ["threat__orden", "measure__orden"],
            },
        ),
        migrations.CreateModel(
            name="MageritAssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("is_terminal", models.BooleanField(default=False)),
                ("ayuda", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_types",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtipos",
                        to="catalog.mageritassettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de activo",
                "verbose_name_plural": "tipos de activo",
                "ordering": ["orden"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog", "code"), name="uniq_asset_type_por_catalogo"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mageritthreat",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_threat_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="mageritthreatdefault",
            constraint=models.UniqueConstraint(
                fields=("threat", "dim"), name="uniq_default_por_dimension"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurethreatmap",
            constraint=models.UniqueConstraint(
                fields=("catalog", "measure", "threat", "dim", "aspect"), name="uniq_salvaguarda"
            ),
        ),
    ]
