# Generated by Django 5.2.17 on 2026-09-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_maturityeffectiveness_mageritthreat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("titulo", models.CharField(max_length=300)),
                ("instrucciones", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DOCUMENTO", "Documento"),
                            ("CAPTURA", "Captura de pantalla"),
                            ("EMAIL", "Correo electrónico"),
                            ("REGISTRO", "Registro o log"),
                            ("CONTRATO", "Contrato o cláusula"),
                            ("CERTIFICADO", "Certificado"),
                            ("FOTO", "Fotografía"),
                            ("EXPORT_CONFIG", "Exportación de configuración"),
                            ("ACTA", "Acta"),
                        ],
                        max_length=15,
                    ),
                ),
                ("formatos", models.JSONField(blank=True, default=list)),
                ("option_group", models.CharField(blank=True, max_length=60)),
                ("preferencia", models.PositiveSmallIntegerField(default=0)),
                ("applies_if", models.JSONField(blank=True, null=True)),
                ("criterios_aceptacion", models.JSONField(blank=True, default=list)),
                ("rechazos_tipicos", models.JSONField(blank=True, default=list)),
                ("obligatoria", models.BooleanField(default=True)),
                ("vigencia_dias", models.PositiveIntegerField(blank=True, null=True)),
                ("carpeta_paquete", models.CharField(blank=True, max_length=120)),
                ("generable", models.BooleanField(default=False)),
                ("ejemplo_url", models.URLField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_templates",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="catalog.ensmeasure",
                    ),
                ),
                (
                    "refuerzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="catalog.ensrefuerzo",
                    ),
                ),
            ],
            options={
                "verbose_name": "plantilla de evidencia",
                "verbose_name_plural": "plantillas de evidencia",
                "ordering": ["measure__orden", "preferencia", "code"],
            },
        ),
        migrations.CreateModel(
            name="EnsCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("descripcion", models.TextField()),
                ("metodo", models.JSONField(default=list)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="catalog.ensrequirementitem",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="catalog.ensmeasure",
                    ),
                ),
                (
                    "refuerzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="catalog.ensrefuerzo",
                    ),
                ),
                (
                    "evidencia_esperada",
                    models.ManyToManyField(
                        blank=True, related_name="checks", to="catalog.evidencetemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "check de verificación",
                "verbose_name_plural": "checks de verificación",
                "ordering": ["measure__orden", "orden"],
            },
        ),
        migrations.CreateModel(
            name="ProductEvidenceHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("producto_match", models.JSONField(default=dict)),
                ("instrucciones", models.TextField()),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="catalog.catalogversion",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pistas_por_producto",
                        to="catalog.evidencetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "pista por producto",
                "verbose_name_plural": "pistas por producto",
            },
        ),
        migrations.CreateModel(
            name="ProfileBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("titulo", models.CharField(max_length=200)),
                ("minutos_estimados", models.PositiveSmallIntegerField(default=0)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to="catalog.catalogversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloque del cuestionario",
                "verbose_name_plural": "bloques del cuestionario",
                "ordering": ["orden", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProfileQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Una opción"),
                            ("MULTI", "Varias opciones"),
                            ("BOOL", "Sí o no"),
                            ("TEXT", "Texto libre"),
                            ("NUMBER", "Número"),
                            ("DATE", "Fecha"),
                            ("TOOL", "Herramienta o producto"),
                            ("VENDOR", "Proveedor"),
                            ("LIST", "Tabla de filas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("texto", models.CharField(max_length=400)),
                ("por_que", models.TextField(blank=True)),
                ("como_saberlo", models.TextField(blank=True)),
                ("a_quien_preguntar", models.CharField(blank=True, max_length=200)),
                ("glosario", models.JSONField(blank=True, default=dict)),
                ("ejemplos", models.JSONField(blank=True, default=list)),
                ("show_if", models.JSONField(blank=True, null=True)),
                ("campos", models.JSONField(blank=True, default=list)),
                ("emits", models.JSONField(blank=True, default=dict)),
                ("funcion", models.CharField(blank=True, max_length=40)),
                ("minutos_estimados", models.PositiveSmallIntegerField(default=1)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "bloque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="catalog.profileblock",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="catalog.catalogversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta de perfilado",
                "verbose_name_plural": "preguntas de perfilado",
                "ordering": ["bloque__orden", "orden"],
            },
        ),
        migrations.CreateModel(
            name="ProfileOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=300)),
                ("emits", models.JSONField(blank=True, default=dict)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="catalog.profilequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "opción de respuesta",
                "verbose_name_plural": "opciones de respuesta",
                "ordering": ["orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="evidencetemplate",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_evidence_template_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("option_group__gt", "")),
                fields=("catalog", "option_group", "preferencia"),
                name="uniq_preferencia_por_grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="enscheck",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_check_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileblock",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_bloque_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilequestion",
            constraint=models.UniqueConstraint(
                fields=("catalog", "code"), name="uniq_pregunta_por_catalogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileoption",
            constraint=models.UniqueConstraint(
                fields=("question", "code"), name="uniq_opcion_por_pregunta"
            ),
        ),
    ]
