# Generated by Django 5.2.17 on 2026-09-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_evidencetemplate_enscheck_productevidencehint_and_more"),
        ("compliance", "0004_measureassessment"),
        ("tenancy", "0003_invitation_membership_dias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="catalog.profilequestion",
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_perfilado",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "respuesta de perfilado",
                "verbose_name_plural": "respuestas de perfilado",
                "ordering": ["question__bloque__orden", "question__orden"],
            },
        ),
        migrations.CreateModel(
            name="ProfileAnswerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("fecha", models.DateTimeField()),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="profiling.profileanswer",
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "respuesta anterior",
                "verbose_name_plural": "historial de respuestas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ProfileDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asignado_email", models.EmailField(blank=True, max_length=254)),
                ("nota", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("RESUELTA", "Resuelta"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preguntas_a_resolver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegaciones",
                        to="catalog.profilequestion",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegaciones_perfilado",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta delegada",
                "verbose_name_plural": "preguntas delegadas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ProfileFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=60)),
                ("value", models.JSONField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "source_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hechos",
                        to="profiling.profileanswer",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hechos",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "hecho del sistema",
                "verbose_name_plural": "hechos del sistema",
                "ordering": ["key"],
            },
        ),
        migrations.AddConstraint(
            model_name="profileanswer",
            constraint=models.UniqueConstraint(
                fields=("system", "question"), name="uniq_respuesta_por_pregunta"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilefact",
            constraint=models.UniqueConstraint(
                fields=("system", "key"), name="uniq_hecho_por_sistema"
            ),
        ),
    ]
