# Generated by Django 5.2.17 on 2026-09-19 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("compliance", "0002_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracionAplicabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADA", "Aprobada"),
                            ("OBSOLETA", "Obsoleta"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                ("categoria", models.CharField(max_length=10)),
                ("niveles", models.JSONField(default=dict)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("aprobada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "aprobador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ddas_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.catalogversion"
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ddas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaraciones",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "declaración de aplicabilidad",
                "verbose_name_plural": "declaraciones de aplicabilidad",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="DimensionValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dim",
                    models.CharField(
                        choices=[
                            ("C", "Confidencialidad"),
                            ("I", "Integridad"),
                            ("T", "Trazabilidad"),
                            ("A", "Autenticidad"),
                            ("D", "Disponibilidad"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("NA", "No aplica"),
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        default="NA",
                        max_length=5,
                    ),
                ),
                ("justificacion", models.TextField(blank=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="compliance.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "valoración de dimensión",
                "verbose_name_plural": "valoraciones de dimensiones",
            },
        ),
        migrations.CreateModel(
            name="InformeCategorizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.UUIDField(unique=True)),
                ("organizacion", models.CharField(blank=True, max_length=200)),
                ("alcance", models.CharField(blank=True, max_length=300)),
                ("niveles", models.JSONField(default=dict)),
                ("categoria", models.CharField(blank=True, max_length=10)),
                ("resumen", models.JSONField(default=dict)),
                ("pdf", models.FileField(blank=True, upload_to="categorizaciones/")),
                ("estado", models.CharField(default="PENDIENTE", max_length=12)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField(blank=True, null=True)),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "informe de categorización",
                "verbose_name_plural": "informes de categorización",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="MeasureApplied",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("aplica", models.BooleanField(default=True)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("justificacion", models.TextField(blank=True)),
                ("compensatoria", models.TextField(blank=True)),
                ("refuerzos_obligatorios", models.JSONField(blank=True, default=list)),
                ("refuerzos_opcionales", models.JSONField(blank=True, default=list)),
                ("refuerzos_elegidos", models.JSONField(blank=True, default=list)),
                ("selecciones", models.JSONField(blank=True, default=dict)),
                (
                    "dda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medidas",
                        to="compliance.declaracionaplicabilidad",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.ensmeasure"
                    ),
                ),
            ],
            options={
                "verbose_name": "medida de la DdA",
                "verbose_name_plural": "medidas de la DdA",
                "ordering": ["measure__orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="declaracionaplicabilidad",
            constraint=models.UniqueConstraint(
                fields=("system", "version"), name="uniq_dda_por_sistema"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimensionvaluation",
            constraint=models.UniqueConstraint(
                fields=("system", "dim"), name="uniq_valoracion_por_dimension"
            ),
        ),
        migrations.AddConstraint(
            model_name="measureapplied",
            constraint=models.UniqueConstraint(
                fields=("dda", "measure"), name="uniq_medida_por_dda"
            ),
        ),
    ]
