# Generated by Django 5.2.17 on 2026-09-19 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_maturityeffectiveness_mageritthreat_and_more"),
        ("compliance", "0003_declaracionaplicabilidad_dimensionvaluation_and_more"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("maturity_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("objetivo", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("applies", models.BooleanField(default=True)),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.ensmeasure"
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medidas_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_medida",
                        to="compliance.system",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "valoración de madurez",
                "verbose_name_plural": "valoraciones de madurez",
                "ordering": ["measure__orden"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "measure"), name="uniq_madurez_por_medida"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("maturity_level__lte", 5)),
                        name="madurez_dentro_de_la_escala",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("objetivo__lte", 5)),
                        name="objetivo_dentro_de_la_escala",
                    ),
                ],
            },
        ),
    ]
